### ISSUE TITLE
Similarity between Graphs

### ISSUE THREAD

**Issue by kinjal20** [caesar0301/graphsim#1]
I want to know that does GraphSim work for the problem as described below:

I have graph G1 and G2 and I want to check how much they are similar structure wise (as like isomorphism property of graph.)

**Comment by akohli96** [comment]
I was wondering the same. Is it possible to get a ratio of similarity? Like how many number of nodes match or something like that?

**Comment by caesar0301** [comment]
@kinjal20  Yes, graphsim actually addresses this problem that how two graphs seem like each other. A portion of shipped algorithm (e.g., SimRank) provide a matrix of nodes and/or edge similarity by considering graph properties, while others give a matrix or unified similarity value (e.g. TACSim).

**Comment by caesar0301** [comment]
@akohli96 well, it may not be the case all the time. Graph similarity tells similarities between all nodes/edges of two graphs. This gives similar information of your ratio.

**Comment by akohli96** [comment]
Thank you @caesar0301 ! I was thinking along the lines of number of nodes matching according to vf2 algorithm or something like that.

**Comment by akohli96** [comment]
@caesar0301 Could you put example code for graph similarity algorithm.

**Comment by kinjal20** [comment]
https://cloud.githubusercontent.com/assets/17423516/25068235/ddd37242-227a-11e7-99cf-96d8d9774538.PNG

Is Graphsim work for this type of problem: no matter content of nodes and edges between them. but as output, it should give similar structure between two input graphs. So may you suggest me if is there any solution for this problem?

**Comment by caesar0301** [comment]
@kinjal20 I think you are addressing a maximum common subgraph problem, https://en.wikipedia.org/wiki/Maximum_common_subgraph. Its a pity this is out the scope of graphsim.

**Comment by caesar0301** [comment]
@akohli96 I have some clues for graph similarity calculation:
1. get node/edge or combined similarity matrix of two graphs (refer to unit test in TACSim.py)
2. feed the similarity matrix into Hungarian algorithm to get the best matching
https://en.wikipedia.org/wiki/Hungarian_algorithm
3. merge the best matching into a similarity score for two graphs, for example, by using normalization
